// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQGTcxzdJKK7qXV-86_Tp-1pdc9DUDVLA',
    appId: '1:93060471361:web:a355cbf32d18c05d3484c0',
    messagingSenderId: '93060471361',
    projectId: 'rideon-rideon',
    authDomain: 'rideon-rideon.firebaseapp.com',
    storageBucket: 'rideon-rideon.firebasestorage.app',
    measurementId: 'G-1W5GSDW4TY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrCZeY116ejRCyRe1LgfcEPuDdFAO-044',
    appId: '1:93060471361:android:4a59eef5f8c2f0683484c0',
    messagingSenderId: '93060471361',
    projectId: 'rideon-rideon',
    storageBucket: 'rideon-rideon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9l3ydJmyInVBhiP704NAUk_gG_ZznbEs',
    appId: '1:93060471361:ios:3c204516ad8daf943484c0',
    messagingSenderId: '93060471361',
    projectId: 'rideon-rideon',
    storageBucket: 'rideon-rideon.firebasestorage.app',
    iosClientId: '93060471361-22rua26i8bnqjebecfh6ln5b26ddht7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQGTcxzdJKK7qXV-86_Tp-1pdc9DUDVLA',
    appId: '1:93060471361:web:035dbc6b9e3fdc3e3484c0',
    messagingSenderId: '93060471361',
    projectId: 'rideon-rideon',
    authDomain: 'rideon-rideon.firebaseapp.com',
    storageBucket: 'rideon-rideon.firebasestorage.app',
    measurementId: 'G-L6297EQNLW',
  );
}
